program soa_sql_templates_editor;

{$mode objfpc}{$H+}

uses
  {$IFDEF UNIX}
  cthreads,
  {$ENDIF}
  Interfaces, // this includes the LCL widgetset
  Forms,
  mormot.db.raw.sqlite3,
  mormot.db.raw.sqlite3.static,
  SqlStatus,
  SqlParamTypes,
  SqlTemplateTypes,
  SqlTemplatesFromDb,
  InfraSqlImplementation,
  AppSqlServices,
  AppSqlClient,
  SqlBounds,
  EditorDb,
  EditorExec,
  RecordDialog,
  { so the editor resolves the types that are compiled into the SERVER as
    well, and not only the ones a RecordDecl column declares. Without it the
    record dialog and the Prüfen button can say nothing about TDtoCustomer -
    the very templates the sample ships }
  WriteDtos,
  TemplateStore,
  DtoCodeGen,
  u_editormain;

// no project .res resource on purpose: that file holds icon and version info,
// is generated by the IDE, and a plain lazbuild would fail without it

begin
  RequireDerivedFormResource := True;
  Application.Initialize;
  Application.CreateForm(TFormEditor, FormEditor);
  Application.Run;
end.
