program soa_sql_templates_client;

{$mode objfpc}{$H+}

uses
  {$IFDEF UNIX}
  cthreads,
  {$ENDIF}
  Interfaces, // this includes the LCL widgetset
  Forms,
  SqlStatus,
  AppSqlServices,
  AppSqlClient,
  ClientDtos,
  u_main;

// no project .res resource on purpose: that file holds icon and version info,
// is generated by the IDE, and a plain lazbuild would fail without it

begin
  RequireDerivedFormResource := True;
  Application.Scaled := True;
  Application.Initialize;
  Application.CreateForm(TFormMain, FormMain);
  Application.Run;
end.
